apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: {{ include "springboot-tekton.fullname" . }}-tb
spec:
  params:
  - name: git-pusher
    value: $(body.pusher-name)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.head_commit.id)