apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  labels:
{{ include "springboot-tekton.labels" . | nindent 4 }}
  name: {{ include "springboot-tekton.fullname" . }}-pipeline
spec:
  workspaces:
  - name: local-maven-repo
  - name: sonar-script
  resources:
  - name: {{ include "springboot-tekton.fullname" . }}-git
    type: git
  - name: {{ include "springboot-tekton.fullname" . }}-templates
    type: git
  - name: {{ include "springboot-tekton.fullname" . }}-image
    type: image
  tasks:

  - name: maven-build
    taskRef: 
      name: maven-build
    resources:
      inputs:
      - name: source
        resource: {{ include "springboot-tekton.fullname" . }}-git
    workspaces:
    - name: maven-repo
      workspace: local-maven-repo

{{- if .Values.sonar.enabled }}
  - name: quality-gate
    taskRef: 
      name: maven-quality
    runAfter:
      - maven-build
    resources:
      inputs:
      - name: source
        resource: {{ include "springboot-tekton.fullname" . }}-git
    params:
    - name: SONAR_HOST_URL
      value: {{ .Values.sonar.url }}
    workspaces:
    - name: maven-repo
      workspace: local-maven-repo
    - name: sonar
      workspace: sonar-script
{{- end}}

  - name: build-image
    taskRef:
      name: buildah
    runAfter: 
      - quality-gate
    resources:
      inputs:
      - name: source
        resource: {{ include "springboot-tekton.fullname" . }}-git
      outputs:
      - name: image
        resource: {{ include "springboot-tekton.fullname" . }}-image
    workspaces:
    - name: maven-repo
      workspace: local-maven-repo

  - name: deploy-to-dev
    taskRef:
      name: deploy
    resources:
      inputs:
      - name: templates
        resource: {{ include "springboot-tekton.fullname" . }}-templates
    runAfter:
      - build-image
    params:
    - name: fromNamespace
      value: {{ .Values.deploy.namespace.prefix }}-build
    - name: toNamespace
      value: {{ .Values.deploy.namespace.prefix }}-dev
    - name: tag
      value: latest
    - name: imageStream
      value: {{ include "springboot-tekton.fullname" . }}
    - name: deployment
      value: {{ include "springboot-tekton.fullname" . }}

  - name: deploy-to-stage
    taskRef:
      name: deploy
    resources:
      inputs:
      - name: templates
        resource: {{ include "springboot-tekton.fullname" . }}-templates
    runAfter:
      - deploy-to-dev
    params:
    - name: fromNamespace
      value: {{ .Values.deploy.namespace.prefix }}-dev
    - name: toNamespace
      value: {{ .Values.deploy.namespace.prefix }}-stage  
    - name: tag
      value: latest 
    - name: imageStream
      value: {{ include "springboot-tekton.fullname" . }} 
    - name: deployment
      value: {{ include "springboot-tekton.fullname" . }} 

  - name: deploy-to-prod
    taskRef:
      name: deploy
    resources:
      inputs:
      - name: templates
        resource: {{ include "springboot-tekton.fullname" . }}-templates
    runAfter:
      - deploy-to-stage
    params:
    - name: fromNamespace
      value: {{ .Values.deploy.namespace.prefix }}-stage
    - name: toNamespace
      value: {{ .Values.deploy.namespace.prefix }}-prod  
    - name: tag
      value: latest 
    - name: imageStream
      value: {{ include "springboot-tekton.fullname" . }} 
    - name: deployment
      value: {{ include "springboot-tekton.fullname" . }}