apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: {{ include "springboot-tekton.fullname" . }}-git
spec:
  type: git
  params:
  - name: url
    value: {{ .Values.git.source.repository }}
  - name: revision
    value: {{ .Values.git.source.revision }}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: {{ include "springboot-tekton.fullname" . }}-templates
spec:
  type: git
  params:
  - name: url
    value: {{ .Values.git.templates.repository }}
  - name: revision
    value: {{ .Values.git.templates.revision }}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: {{ include "springboot-tekton.fullname" . }}-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{ include "springboot-tekton.fullname" . }}