apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  labels:
{{ include "springboot-tekton.labels" . | nindent 4 }}
  name: maven-quality
spec:
  workspaces:
  - name: maven-repo
  - name: sonar
  inputs:
    params:
    - name: GOALS
      description: The Maven goals to run
      type: array
      default: ["sonar:sonar"]
    - name: SONAR_HOST_URL
      description: the sonar host URL
      type: string
    resources:
    - name: source
      type: git
  steps: 

  - name: copy-target-dir
    image: registry.redhat.io/ubi8/ubi-minimal:8.2
    workingDir: /workspace/source
    command:
    - cp
    args:
    - -r
    - /workspace/maven-repo/shift-rest-target
    - /workspace/source/target
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi

  - name: sonar-scan
    image: maven:3.6.0-jdk-8-slim
    workingDir: /workspace/source
    command:
    - /usr/bin/mvn
    args:
    - -Dmaven.repo.local=$(workspaces.maven-repo.path)
    - "-Dsonar.host.url=$(inputs.params.SONAR_HOST_URL)"
    - "$(inputs.params.GOALS)"
    resources:
      limits:
        cpu: 0.5
        memory: 1Gi

  - name: quality-gate
    image: quay.io/sychen/openshift-cli-jq:latest
    command: ["bash"]
    workingDir: /workspace/source
    args:
      - $(workspaces.sonar.path)/sonar.sh
    resources:
      limits:
        cpu: 0.25
        memory: 0.5Gi