apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  labels:
{{ include "springboot-tekton.labels" . | nindent 4 }}
  name: maven-build-binary-build
spec:
  workspaces:
  - name: maven-repo
  inputs:
    params:
    - name: GOALS
      description: The Maven goals to run
      type: array
      default: ["package"]
{{- if .Values.sonar.enabled }}
    - name: volumeName
      description: The sonar-script volume
      type: string
      default: sonar-volume
    - name: CFGNAME
      description: the sonar config map name containing the quality gate script
      type: string
      default: sonar
{{- end }}
    resources:
    - name: source
      type: git
  steps:   
  - name: package
    image: {{ .Values.maven.image.repository }}:{{ .Values.maven.image.tag }}
    workingDir: /workspace/source
    command:
    - {{ .Values.maven.command }}
    args:
    - -Dmaven.repo.local=$(workspaces.maven-repo.path)
    - "$(inputs.params.GOALS)"
{{- if .Values.sonar.enabled }}
  - name: sonar-scan
    image: {{ .Values.maven.image.repository }}:{{ .Values.maven.image.tag }}
    workingDir: /workspace/source
    command:
    - {{ .Values.maven.command }}
    args:
    - -Dmaven.repo.local=$(workspaces.maven-repo.path)
    - -Dsonar.host.url={{ .Values.sonar.url }}
    - sonar:sonar
  - name: quality-gate
    image: quay.io/sychen/openshift-cli-jq:latest
    command: ["bash"]
    workingDir: /workspace/source
    args:
      - /var/sonar/sonar.sh
    volumeMounts:
    - name: "$(inputs.params.volumeName)"
      mountPath: /var/sonar
{{- end }}
  - name: make-upload-dir
    image: quay.io/openshift-pipeline/openshift-cli:latest
    command: ["mkdir"]
    args:
      - -p
      - /workspace/source/upload
  - name: copy-assets 
    image: quay.io/openshift-pipeline/openshift-cli:latest
    command: ["cp"]
    args:
      - /workspace/source/target/shift-rest-1.0.0-SNAPSHOT.jar
      - /workspace/source/upload 
  - name: oc-binary-build 
    image: quay.io/openshift-pipeline/openshift-cli:latest
    command: ["/usr/local/bin/oc"]
    workingDir: /workspace/source/upload
    args:
      - start-build
      - -w
      - -F
      - {{ include "springboot-tekton.fullname" . }}
      - --from-dir
      - "."
{{- if .Values.sonar.enabled }}
  volumes:
  - name: "$(inputs.params.volumeName)"
    configMap:
      name: "$(inputs.params.CFGNAME)"
{{- end }}