apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
{{ include "springboot-tekton.labels" . | nindent 4 }}
  name: maven-quality
spec:

  params:
  - name: GOALS
    description: The Maven goals to run
    type: array
    default: ["sonar:sonar"]
  - name: VOLUMENAME
    description: The sonar-script volume
    type: string
    default: sonar-volume
  - name: CFGNAME
    description: the sonar config map name containing the quality gate script
    type: string
    default: sonar
  - name: SONAR_HOST_URL
    description: the sonar host URL
    type: string
  resources:
    inputs:
    - name: source
      type: git
  steps: 

  - name: package
    image: maven:3.6.0-jdk-8-slim
    workingDir: /workspace/source
    command:
    - /usr/bin/mvn
    args:
    - -Dmaven.repo.local=$(workspaces.maven-repo.path)
    - -DskipTests
    - package
    resources:
      limits:
        cpu: 0.5
        memory: 1Gi

  - name: sonar-scan
    image: maven:3.6.0-jdk-8-slim
    workingDir: /workspace/source
    command:
    - /usr/bin/mvn
    args:
    - -Dmaven.repo.local=$(workspaces.maven-repo.path)
    - "-Dsonar.host.url=$(params.SONAR_HOST_URL)"
    - "$(params.GOALS)"
    resources:
      limits:
        cpu: 0.5
        memory: 1Gi

  - name: quality-gate
    image: quay.io/sychen/openshift-cli-jq:latest
    command: ["bash"]
    workingDir: /workspace/source
    args:
      - /var/sonar/sonar.sh
    volumeMounts:
    - name: "$(params.VOLUMENAME)"
      mountPath: /var/sonar
    resources:
      limits:
        cpu: 0.25
        memory: 0.5Gi

  volumes:
  - name: "$(params.VOLUMENAME)"
    configMap:
      name: "$(params.CFGNAME)"
  workspaces:
  - name: maven-repo