apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  labels:
{{ include "springboot-tekton.labels" . | nindent 4 }}
  name: maven-build
spec:
  workspaces:
  - name: maven-repo
  inputs:
    params:
    - name: GOALS
      description: The Maven goals to run
      type: array
      default: ["package"]
    resources:
    - name: source
      type: git
  steps: 

  - name: package
    image: maven:3.6.0-jdk-8-slim
    workingDir: /workspace/source
    command:
    - /usr/bin/mvn
    args:
    - -Dmaven.repo.local=$(workspaces.maven-repo.path)
    - "$(inputs.params.GOALS)"
    resources:
      limits:
        cpu: 1
        memory: 2Gi

  - name: copy-target-dir
    image: registry.redhat.io/ubi8/ubi-minimal:8.2
    workingDir: /workspace/source
    command:
    - cp
    args:
    - -r
    - ./target/
    - /workspace/maven-repo/shift-rest-target
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi